title: "Homer"
subtitle: "DashBoard"
logo: "logo.png"
header: false

footer: '<p>Theme made with <span class="has-text-danger">❤</span> by <a href="https://github.com/lSukiChanl">SukiChan</a></p>'

stylesheet:
  - "assets/custom.css"

columns: "3"
theme: default
colors:
  
  light:
    highlight-primary: "#fff5f2"
    highlight-secondary: "#fff5f2"
    highlight-hover: "#bebebe"
    background: "#12152B"
    card-background: "rgba(255, 245, 242, 0.8)"
    text: "#ffffff"
    text-header: "#fafafa"
    text-title: "#000000"
    text-subtitle: "#111111"
    card-shadow: rgba(0, 0, 0, 0.5)
    link: "#3273dc"
    link-hover: "#2e4053"
    background-image: "../assets/wallpaper-light.jpeg"
  
  dark:
    highlight-primary: "#181C3A"
    highlight-secondary: "#181C3A"
    highlight-hover: "#1F2347"
    background: "#12152B"
    card-background: "rgba(24, 28, 58, 0.8)"
    text: "#eaeaea"
    text-header: "#7C71DD"
    text-title: "#fafafa"
    text-subtitle: "#8B8D9C"
    card-shadow: rgba(0, 0, 0, 0.5)
    link: "#c1c1c1"
    link-hover: "#fafafa"
    background-image: "../assets/wallpaper.jpeg"

services:
  
  - name: "♡ My Services ♡"
    icon: "fas fa-heart"
    items:
      - name: "My Github SukiChan"
        logo: "assets/tools/Menhera.png"
        subtitle: "Welcome to my Github!"
        tag: "Github"
        tagstyle: "is-sponsor"
        url: "https://github.com/lSukiChanl"
        target: "_blank"

  - name: " Youtube "
    icon: "fab fa-youtube"
    items:
      - name: "Minami 美波「LILA」MV"
        logo: "assets/tools/Youtube.png"
        subtitle: "My Favorite Song"
        tag: "Music"
        tagstyle: "is-sponsor"
        url: "https://www.youtube.com/watch?v=GQ3V50XoLOM"
        target: "_blank"

  - name: "Favorites"
    icon: "fas fa-star"
    items:
      - name: "Google"
        logo: "assets/tools/Google.png"
        subtitle: "Nothing to say... just Google"
        tag: "Search"
        tagstyle: "is-sponsor"
        url: "https://www.google.com/"
        target: "_blank"